# Generated by Django 6.1.1 on 2026-09-15 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APISpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('version', models.CharField(blank=True, max_length=80)),
                ('content', models.JSONField()),
                ('raw_text', models.TextField(blank=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('new_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_comparisons', to='api_app.apispecification')),
                ('old_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_comparisons', to='api_app.apispecification')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='APIChangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_id', models.CharField(db_index=True, max_length=32)),
                ('change_type', models.CharField(max_length=120)),
                ('category', models.CharField(default='contract', max_length=80)),
                ('endpoint', models.CharField(max_length=300)),
                ('method', models.CharField(blank=True, max_length=16)),
                ('direction', models.CharField(default='unknown', max_length=40)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('parameter', models.CharField(blank=True, max_length=200)),
                ('schema_path', models.CharField(blank=True, max_length=300)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('compatibility', models.CharField(default='unknown', max_length=40)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.JSONField(blank=True, default=dict)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='api_app.comparison')),
            ],
            options={
                'ordering': ('endpoint', 'method', 'change_type', 'parameter'),
                'unique_together': {('comparison', 'change_id')},
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(max_length=40)),
                ('source', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('excerpt', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='api_app.apichangerecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImpactReportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.CharField(max_length=40)),
                ('severity', models.CharField(max_length=20)),
                ('affected_components', models.JSONField(blank=True, default=list)),
                ('impact', models.TextField()),
                ('recommendation', models.TextField()),
                ('change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impact_reports', to='api_app.apichangerecord')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_reports', to='api_app.comparison')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MigrationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
                ('steps', models.JSONField(blank=True, default=list)),
                ('versioning_recommendation', models.TextField()),
                ('rollback', models.TextField(blank=True)),
                ('comparison', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='migration_plan', to='api_app.comparison')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='comparison',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='api_app.project'),
        ),
        migrations.AddField(
            model_name='apispecification',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='api_app.project'),
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('comparison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_jobs', to='api_app.comparison')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='api_app.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_identifier', models.CharField(max_length=300)),
                ('target_identifier', models.CharField(max_length=300)),
                ('relationship', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='api_app.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'source_identifier'], name='api_app_dep_project_8124cf_idx'), models.Index(fields=['project', 'target_identifier'], name='api_app_dep_project_23044d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('consumer_type', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumers', to='api_app.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['project', 'status'], name='api_app_com_project_5a1b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='apispecification',
            index=models.Index(fields=['project', 'content_hash'], name='api_app_api_project_30bf39_idx'),
        ),
    ]
