# Generated by Codex on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="impactreportrecord",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="impactreportrecord",
            name="confidence",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="impactreportrecord",
            name="llm_status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="impactreportrecord",
            name="llm_error",
            field=models.TextField(blank=True),
        ),
    ]
