# Generated by Django 6.1.1 on 2026-09-19 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_impactreportrecord_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=120)),
                ('resource_type', models.CharField(max_length=120)),
                ('resource_id', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GitHubConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation_id', models.CharField(db_index=True, max_length=100)),
                ('repository_full_name', models.CharField(max_length=300)),
                ('connected', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('token_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_id', models.CharField(max_length=150)),
                ('endpoint', models.CharField(blank=True, max_length=300)),
                ('target', models.CharField(blank=True, max_length=300)),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='error_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='error_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='stage',
            field=models.CharField(choices=[('queued', 'Queued'), ('ingest', 'Ingest'), ('quality', 'Quality'), ('normalize', 'Normalize'), ('diff', 'Diff'), ('rules', 'Rules'), ('policy', 'Policy'), ('gate', 'Gate'), ('evidence', 'Evidence'), ('explanation', 'Explanation'), ('publish', 'Publish'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=30),
        ),
        migrations.AddField(
            model_name='apichangerecord',
            name='flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='apichangerecord',
            name='relation',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='apichangerecord',
            name='rule_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='apichangerecord',
            name='stable_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='apispecification',
            name='commit_sha',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='apispecification',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apispecification',
            name='openapi_version',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='apispecification',
            name='path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='apispecification',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apispecification',
            name='repository',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='apispecification',
            name='source_type',
            field=models.CharField(choices=[('generated', 'Generated'), ('committed', 'Committed'), ('published', 'Published'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='comparison',
            name='analyzer_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='comparison',
            name='base_sha',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='comparison',
            name='base_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_comparisons', to='api_app.apispecification'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='baseline_mode',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='comparison',
            name='gate_reason_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='comparison',
            name='gate_status',
            field=models.CharField(blank=True, choices=[('PASS', 'Pass'), ('WARN', 'Warn'), ('FAIL', 'Fail'), ('ERROR', 'Error')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='head_sha',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='comparison',
            name='head_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_comparisons', to='api_app.apispecification'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='llm_model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comparison',
            name='policy_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='comparison',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='comparison',
            name='pull_request_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='quality_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='comparison',
            name='repository',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='comparison',
            name='rules_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='comparison',
            name='summary_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evidence',
            name='retrieval',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='impactreportrecord',
            name='confidence_label',
            field=models.CharField(default='estimated', max_length=30),
        ),
        migrations.AddField(
            model_name='impactreportrecord',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='impactreportrecord',
            name='evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='impactreportrecord',
            name='input_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='impactreportrecord',
            name='model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='impactreportrecord',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='impactreportrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='adapter_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='baseline_mode',
            field=models.CharField(default='merge_base', max_length=40),
        ),
        migrations.AddField(
            model_name='project',
            name='default_branch',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='error_mode',
            field=models.CharField(choices=[('fail_closed', 'Fail Closed'), ('fail_open', 'Fail Open')], default='fail_closed', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='fail_severity_threshold',
            field=models.CharField(default='high', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='min_quality_score',
            field=models.PositiveSmallIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='project',
            name='potentially_breaking_policy',
            field=models.CharField(choices=[('warn', 'Warn'), ('fail', 'Fail')], default='warn', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='repository_full_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='response_added_required_policy',
            field=models.CharField(choices=[('tolerant_reader', 'Tolerant Reader'), ('strict', 'Strict')], default='tolerant_reader', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='spec_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='impactreportrecord',
            name='impact',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='impactreportrecord',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='apichangerecord',
            index=models.Index(fields=['comparison', 'stable_hash'], name='api_app_api_compari_968876_idx'),
        ),
        migrations.AddIndex(
            model_name='apichangerecord',
            index=models.Index(fields=['comparison', 'rule_id'], name='api_app_api_compari_9a1220_idx'),
        ),
        migrations.AddIndex(
            model_name='apispecification',
            index=models.Index(fields=['project', 'commit_sha'], name='api_app_api_project_0a686d_idx'),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['repository', 'head_sha'], name='api_app_com_reposit_106aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['project', 'base_sha', 'head_sha'], name='api_app_com_project_a0b0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='impactreportrecord',
            index=models.Index(fields=['comparison', 'status'], name='api_app_imp_compari_a7e764_idx'),
        ),
        migrations.AddIndex(
            model_name='impactreportrecord',
            index=models.Index(fields=['change', 'input_hash'], name='api_app_imp_change__edb463_idx'),
        ),
        migrations.AddConstraint(
            model_name='comparison',
            constraint=models.UniqueConstraint(fields=('project', 'idempotency_key'), name='unique_comparison_project_idempotency'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api_app.project'),
        ),
        migrations.AddField(
            model_name='githubconnection',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_connection', to='api_app.project'),
        ),
        migrations.AddField(
            model_name='projecttoken',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='api_app.project'),
        ),
        migrations.AddField(
            model_name='waiver',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_api_waivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waiver',
            name='comparison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='api_app.comparison'),
        ),
        migrations.AddIndex(
            model_name='projecttoken',
            index=models.Index(fields=['project', 'revoked_at'], name='api_app_pro_project_7901e8_idx'),
        ),
        migrations.AddIndex(
            model_name='waiver',
            index=models.Index(fields=['comparison', 'rule_id'], name='api_app_wai_compari_f7806c_idx'),
        ),
    ]
