"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = os.getenv(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1,testserver",
).split(",")

CORS_ALLOWED_ORIGINS = [
    "https://openapianalyzer.netlify.app",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CSRF_TRUSTED_ORIGINS = [
    "https://openapianalyzer.netlify.app",
]


# ============================================================
# API ANALYZER EXECUTION SETTINGS
# ============================================================

# Background worker execution.
#
# Current Render Free deployment does not have a separate worker,
# so keep this disabled for now.
#
# Later, when a background worker is deployed:
# API_ANALYZER_WORKER_ENABLED=true
API_ANALYZER_WORKER_ENABLED = (
    os.getenv("API_ANALYZER_WORKER_ENABLED", "false").lower() == "true"
)


# Maximum size of each individual OpenAPI specification.
#
# Base specification: <= 5 MB
# Head specification: <= 5 MB
API_ANALYZER_MAX_SPEC_BYTES = int(
    os.getenv(
        "API_ANALYZER_MAX_SPEC_BYTES",
        str(5 * 1024 * 1024),
    )
)


# Maximum number of API operations allowed in each specification.
#
# This prevents very large contracts from consuming excessive
# CPU/memory during comparison.
API_ANALYZER_MAX_OPERATIONS = int(
    os.getenv(
        "API_ANALYZER_MAX_OPERATIONS",
        "200",
    )
)


# Maximum amount of time allowed for synchronous analysis.
#
# Keep this below the Gunicorn request timeout that we will configure
# later.
API_ANALYZER_SYNC_MAX_RUNTIME_SECONDS = int(
    os.getenv(
        "API_ANALYZER_SYNC_MAX_RUNTIME_SECONDS",
        "90",
    )
)


# Maximum time a queued CI job may remain unprocessed.
#
# This prevents GitHub Actions from polling forever when no worker
# is available.
API_ANALYZER_QUEUED_MAX_AGE_SECONDS = int(
    os.getenv(
        "API_ANALYZER_QUEUED_MAX_AGE_SECONDS",
        "60",
    )
)


# Maximum complete CI request size.
#
# Two specifications can each be up to 5 MB, so 8 MB is too small.
# 16 MB gives enough room for both specifications plus metadata.
API_ANALYZER_MAX_CI_BODY_BYTES = int(
    os.getenv(
        "API_ANALYZER_MAX_CI_BODY_BYTES",
        str(16 * 1024 * 1024),
    )
)


# ============================================================
# GITHUB APP INTEGRATION
# ============================================================
# Keep all GitHub App secrets in environment variables. Never commit
# the private key or client secret to the repository.
GITHUB_APP_ID = os.getenv("GITHUB_APP_ID", "")
GITHUB_APP_SLUG = os.getenv("GITHUB_APP_SLUG", "")
GITHUB_APP_CLIENT_ID = os.getenv("GITHUB_APP_CLIENT_ID", "")
GITHUB_APP_CLIENT_SECRET = os.getenv("GITHUB_APP_CLIENT_SECRET", "")
GITHUB_APP_PRIVATE_KEY = os.getenv("GITHUB_APP_PRIVATE_KEY", "")
GITHUB_APP_CALLBACK_URL = os.getenv(
    "GITHUB_APP_CALLBACK_URL",
    "http://localhost:8000/api/github/install/callback/",
)
GITHUB_APP_FRONTEND_URL = os.getenv(
    "GITHUB_APP_FRONTEND_URL",
    "http://localhost:5173",
).rstrip("/")
GITHUB_API_URL = os.getenv(
    "GITHUB_API_URL",
    "https://api.github.com",
).rstrip("/")
GITHUB_API_VERSION = os.getenv(
    "GITHUB_API_VERSION",
    "2026-03-10",
)
GITHUB_API_TIMEOUT_SECONDS = float(
    os.getenv("GITHUB_API_TIMEOUT_SECONDS", "15")
)
GITHUB_INSTALL_STATE_TTL_SECONDS = int(
    os.getenv("GITHUB_INSTALL_STATE_TTL_SECONDS", "600")
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'auth_app',
    'api_app',
    "corsheaders",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

import dj_database_url

DATABASES = {
    "default": dj_database_url.parse(
        os.getenv(
            "DATABASE_URL",
            f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        ),
        conn_max_age=600,
        ssl_require=False,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}