"""
Registry for API contract sources.

The registry keeps contract acquisition pluggable. The compatibility
engine does not need to know whether a contract was committed directly,
generated by Django REST Framework, or obtained by another integration.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Iterable, Mapping

from .base import ContractSource


@dataclass(frozen=True)
class ContractSourceResolution:
    """
    Result of resolving a repository to a contract source.
    """

    supported: bool
    source: ContractSource | None = None
    reason: str = ""
    errors: tuple[str, ...] = ()


class ContractSourceRegistry:
    """
    Registry containing all supported contract-source implementations.
    """

    def __init__(
        self,
        sources: Iterable[ContractSource] | None = None,
    ) -> None:
        self._sources: dict[str, ContractSource] = {}

        for source in sources or ():
            self.register(source)

    def register(self, source: ContractSource) -> None:
        """
        Register a contract source.

        Each source_type must be unique.
        """

        source_type = source.source_type.strip()

        if not source_type:
            raise ValueError(
                "Contract source_type cannot be empty."
            )

        if source_type in self._sources:
            raise ValueError(
                f"Contract source '{source_type}' is already registered."
            )

        self._sources[source_type] = source

    def get(self, source_type: str) -> ContractSource:
        """
        Return a registered contract source by type.
        """

        try:
            return self._sources[source_type]
        except KeyError as exc:
            raise KeyError(
                f"Unknown contract source: {source_type}"
            ) from exc

    def has(self, source_type: str) -> bool:
        """
        Return whether a source type is registered.
        """

        return source_type in self._sources

    def all(self) -> tuple[ContractSource, ...]:
        """
        Return all registered sources in deterministic order.
        """

        return tuple(self._sources.values())

    def types(self) -> tuple[str, ...]:
        """
        Return all registered source types.
        """

        return tuple(self._sources.keys())

    def __len__(self) -> int:
        return len(self._sources)

    def __iter__(self):
        return iter(self._sources.values())

    def resolve(
        self,
        repository: Mapping[str, Any],
        *,
        spec_path: str | None = None,
    ) -> ContractSourceResolution:
        """
        Resolve the first compatible contract source.

        Resolution order is deterministic and follows registration order.
        Source errors are collected instead of silently being discarded.
        """

        errors: list[str] = []

        for source in self._sources.values():
            try:
                if source.can_resolve(
                    repository,
                    spec_path=spec_path,
                ):
                    return ContractSourceResolution(
                        supported=True,
                        source=source,
                        reason=(
                            f"Contract source '{source.source_type}' "
                            "can resolve the repository."
                        ),
                    )
            except Exception as exc:
                errors.append(
                    f"{source.source_type}: {exc}"
                )

        if errors:
            reason = (
                "No contract source could resolve the repository. "
                "One or more sources returned errors."
            )
        else:
            reason = (
                "No registered contract source can resolve "
                "the repository."
            )

        return ContractSourceResolution(
            supported=False,
            source=None,
            reason=reason,
            errors=tuple(errors),
        )

    def metadata(self) -> tuple[Mapping[str, Any], ...]:
        """
        Return metadata for all registered contract sources.
        """

        return tuple(
            source.metadata()
            for source in self._sources.values()
        )

    @classmethod
    def with_defaults(cls) -> "ContractSourceRegistry":
        """
        Build the default contract-source registry.

        The committed source is registered first because an already
        committed contract is directly reproducible at a repository
        revision and does not require application execution.

        Framework-specific sources are then registered for repositories
        where contract generation is required.
        """

        from .committed import CommittedContractSource
        from .drf import DjangoRESTFrameworkContractSource

        registry = cls()

        registry.register(
            CommittedContractSource()
        )

        registry.register(
            DjangoRESTFrameworkContractSource()
        )

        return registry